# -----------------------------------------------------------------------------
# openapi/paths/auth/auth-logout.openapi.yaml
# -----------------------------------------------------------------------------

# PATCH /auth/logout
patch:
  tags:
    - Auth
  summary: Social Logout
  description: 해당 유저를 로그아웃 처리합니다.
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../components/schemas/auth/auth.schema.yaml"
  responses:
    "200":
      $ref: "../../components/responses/auth/logoutSuccess.res.yaml"
    "404":
      content:
        application/json:
          examples:
            fcmToken을 안 넣음:
              value:
                status: 404
                success: false
                message: 존재하지 않는 자원
            DB에 존재하지 않는 fcmToken:
              value:
                status: 404
                success: false
                message: 존재하지 않는 fcm Token 입니다.
    "500":
      $ref: "../../components/responses/global/internalServerError.res.yaml"
