# -----------------------------------------------------------------------------
# openapi/paths/records/record-storage-list.openapi.yaml
# -----------------------------------------------------------------------------

# GET /record/storage/list?filter=
get:
  tags:
    - Records
  summary: Storage(list)
  description: >
    Storage(list)
  parameters:
    - $ref: "../../components/parameters/authorization.param.yaml"
    - $ref: "../../components/parameters/listFilter.param.yaml"
  responses:
    "200":
      $ref: "../../components/responses/records/readRecordStorageSuccess.res.yaml"
    "400":
      $ref: "../../components/responses/records/readRecordStorageFail.res.yaml"
    "401":
      $ref: "../../components/responses/global/noUser.res.yaml"
    "500":
      $ref: "../../components/responses/global/internalServerError.res.yaml"
