# -----------------------------------------------------------------------------
# openapi/paths/user/user-fcmToken.openapi.yaml
# -----------------------------------------------------------------------------

# PUT /user/fcm-token
put:
  tags:
    - User
  summary: Refresh User's fcmToken
  description: Refresh User's fcmToken
  parameters:
    - $ref: "../../components/parameters/authorization.param.yaml"
  requestBody:
    description: originToken = 원래의 fcm Token, newToken = 변경할 fcm Token
    content:
      application/json:
        schema:
          $ref: "../../components/schemas/user/user-fcmToken.schema.yaml"
  responses:
    "200":
      $ref: "../../components/responses/user/updatefcmTokenSuccess.res.yaml"
    "404":
      content:
        application/json:
          examples:
            존재하지 않는 유저:
              value:
                status: 404
                success: false
                message: 필요한 값이 없습니다.
            입력한 originToken이 DB에 없음:
              value:
                status: 404
                success: false
                message: 존재하지 않는 fcm Token 입니다.
    "500":
      $ref: "../../components/responses/global/internalServerError.res.yaml"
