# -----------------------------------------------------------------------------
# openapi/paths/user/user.openapi.yaml
# -----------------------------------------------------------------------------

# DELETE /user
delete:
  tags:
    - User
  summary: Delete User
  description: Delete User
  parameters:
    - $ref: "../../components/parameters/authorization.param.yaml"
  responses:
    "200":
      $ref: "../../components/responses/user/deleteUserSuccess.res.yaml"
    "401":
      $ref: "../../components/responses/global/noUser.res.yaml"
    "500":
      $ref: "../../components/responses/global/internalServerError.res.yaml"

# GET /user
get:
  tags:
    - User
  summary: Get User
  description: Get User
  parameters:
    - $ref: "../../components/parameters/authorization.param.yaml"
  responses:
    "200":
      $ref: "../../components/responses/user/getUserSuccess.res.yaml"
    "404":
      $ref: "../../components/responses/global/notFound.res.yaml"
    "500":
      $ref: "../../components/responses/global/internalServerError.res.yaml"
